AllCops:
  Exclude:
    - "spec/**/*"
    - "vendor/**/*"
  TargetRubyVersion: 2.3

Layout:
  Enabled: false

Metrics:
  Enabled: false

Style:
  Enabled: false

# Configuration to look into removing:

Lint/EmptyWhen:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Performance/UnfreezeString:
  Enabled: false

Naming/MethodName:
  Enabled: false
