sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.0
  - 2.4.2
  - 2.3.5
  - 2.2.8
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_install: gem install bundler -v 1.16.1
script:
  - bundle exec rake ci
